apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugo-cloud-deployment
  labels:
    app: node-redis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-redis
  template:
    metadata:
      labels:
        app: node-redis
    spec:
      containers:
        - name: node-redis-container
          image: cloud.canister.io:5000/arhturescriou/node-redis
          env:
            - name: PORT
              value: "6379"
            - name: REDIS_URL
              value: "redis://hugo-redis-service:6379"
          ports:
            - containerPort: 6379  
      imagePullSecrets:
        - name: regcred
